### ISSUE TITLE
WriteAt should be implemented for &RandomAccessFile

### ISSUE THREAD

**Issue by Dr-Emann** [vasi/positioned-io#11]
Like [std::io::Write](https://doc.rust-lang.org/std/io/trait.Write.html#impl-Write-10) is implemented for &File, WriteAt should also be implemented for &RandomAccessFile, to allow WriteAt on files without needing a mutable reference.

**Comment by niklasf** [comment]
Same for ReatAt.

**Comment by Dr-Emann** [comment]
I think ReadAt is less important, since the functions on ReadAt take `&self` anyway. I suppose there should be a blanket `impl<R: ReadAt> ReadAt for &R { ... }`, which would also handle RandomAccessFile
