### ISSUE TITLE
Windows read_at implementation is very slow

### ISSUE THREAD

**Issue by Dr-Emann** [vasi/positioned-io#6]
The [implementation of ReadAt](https://github.com/vasi/positioned-io/blob/4c67b8ffd407498d10453b228c37fe7d20f66fcb/src/windows.rs#L52) for windows is very slow. Benchmarks are [here](https://github.com/Dr-Emann/positioned-io/blob/benchmark/benches/my_benchmark.rs), and a violin graph from a run is attached:
![violin](https://user-images.githubusercontent.com/1153779/47946585-fab66500-dee3-11e8-9ac1-7655b6d8bd34.png)

The memory map based implementation currently used is about an order of magnitude slower than using a refcell. Even faster is to use [`seek_read`](https://doc.rust-lang.org/std/os/windows/fs/trait.FileExt.html#tymethod.seek_read) (which does change the current offset in the file.

I personally would use the `seek_read` function, and  document that uses of `ReadAt` may or may not change the current file offset.

**Comment by niklasf** [comment]
Mhh, yeah ... if there is no other way, like somehow keeping the memory map alive instead of repeated mapping and unmapping, that might be best.

Meanwhile the currently released positioned-io 0.2 still essentially uses seek_read.

**Comment by Dr-Emann** [comment]
I don't think so, at least not implemented directly on `File`. It could be done as a wrapper around file which also implements `ReadAt`, but doesn't move the file pointer.

**Comment by niklasf** [comment]
I added a wrapper that simply uses `seek_read` (`RandomAccessFile`) and released it as `positioned-io-preview = "0.3.1"`. It implements `ReadAt` but not `Read`.

It is possible to observe the moving cursor by constructing another `File` handle with the same file descriptor, but at least the wrapper makes you think twice.
